import { HardhatUserConfig } from "hardhat/config";
import { HardhatConfig } from "hardhat/types/config";
import { HardhatUserConfigValidationError } from "hardhat/types/hooks";

/**
 * This function validates the parts of the HardhatUserConfig that are relevant
 * to the plugin.
 *
 * This function is called from the `validateUserConfig` Hook Handler.
 *
 * @param userConfig The HardhatUserConfig, as exported in the config file.
 * @returns An array of validation errors, or an empty array if valid.
 */
export async function validatePluginConfig(
  userConfig: HardhatUserConfig,
): Promise<HardhatUserConfigValidationError[]> {
  const errors: HardhatUserConfigValidationError[] = [];

  // Validate openScan config
  if (userConfig.openScan !== undefined) {
    if (typeof userConfig.openScan !== "object") {
      errors.push({
        path: ["openScan"],
        message: "Expected an object with optional url and chainId.",
      });
    } else {
      const { url, chainId } = userConfig.openScan;

      if (url !== undefined && (typeof url !== "string" || url.length === 0)) {
        errors.push({
          path: ["openScan", "url"],
          message: "Expected a non-empty string.",
        });
      }

      if (
        chainId !== undefined &&
        (typeof chainId !== "number" || chainId < 0)
      ) {
        errors.push({
          path: ["openScan", "chainId"],
          message: "Expected a positive number.",
        });
      }
    }
  }

  return errors;
}

/**
 * Resolves the plugin config, based on an already validated HardhatUserConfig
 * and a partially resolved HardhatConfig.
 *
 * This function is called from the `resolveUserConfig` Hook Handler.
 *
 * @param userConfig The HardhatUserConfig.
 * @param partiallyResolvedConfig The partially resolved HardhatConfig, which is
 *  generated by calling `next` in the `resolveUserConfig` Hook Handler.
 * @returns The resolved HardhatConfig.
 */
export async function resolvePluginConfig(
  userConfig: HardhatUserConfig,
  partiallyResolvedConfig: HardhatConfig,
): Promise<HardhatConfig> {
  const url = userConfig.openScan?.url ?? "http://localhost:3030";
  const chainId = userConfig.openScan?.chainId ?? 31337;
  const openScan = { url, chainId };

  return {
    ...partiallyResolvedConfig,
    openScan,
  };
}
